### ISSUE TITLE
autofix should be an argument

### ISSUE THREAD

**Issue by caldempsey** [fernandrone/linelint#13]
Hi!

Great tool, difficult to split lint from lint-fix runs. Is there an idiom to support this e.g. linelint --fix?

**Comment by fernandrone** [comment]
Hey @caldempsey , sorry for the delay. I had not been actively maintaining this repository this and ended up missing the notification.

There's a flag already (`-a`, stands for "autofix") which should do exactly that. It should override the value set in the configuration file (if you have any). So you could set the configuration file to `autofix: false` and then run `linelint -a` when you want to fix everything 👍🏻 

```
linelint --help
usage of linelint [-a] [FILE_OR_DIR [FILE_OR_DIR ...]]

Validates simple newline and whitespace rules in all sorts of files.

positional arguments:
  FILE_OR_DIR		files to format or '-' for stdin

optional arguments:
  -a	(autofix) will automatically fix files with errors in place
```

Does that help?

**Comment by fernandrone** [comment]
Closing this as I believe `-a` should solve the issue. Please ask to reopen if required.
